### ISSUE TITLE
Server's are unavailable 

### ISSUE THREAD

**Issue by ZOLAAAA115** [abdlhay/Manga_slayer#1]
![Screenshot_20241231_120951_Manga Slayer](https://github.com/user-attachments/assets/91798a5e-e610-4d64-a085-ebcfad343795)

**Comment by abdlhay** [comment]
I'm working on it. I completely forgot its the end of the year and certificate was expired 
it will be fixed in 15 minutes from now

**Comment by ZOLAAAA115** [comment]
Thank you so much i really appreciate the work you are doing 🤍✨
